/**
 * reports.js
 * CRUD operations for Financial Reports.
 * Add, Edit, Delete, View — reflected in the UI without page reloads.
 */

import FinanceDB, { persistData } from "../data/mockData.js";
import { showToast, openModal, badgeHTML, formatCurrency, generateId, validateForm, showFieldError, clearAllErrors, formatDate, can } from "../utils/utils.js";
import { logActivity } from "./activity.js";

/* ── RENDER LIST ──────────────────────────────────── */

export function renderReportList(filter = {}) {
  const tbody = document.getElementById("reports-tbody");
  if (!tbody) return;

  let records = [...FinanceDB.financialReports];

  if (filter.category && filter.category !== "all") {
    records = records.filter(r => r.category === filter.category);
  }
  if (filter.status && filter.status !== "all") {
    records = records.filter(r => r.status === filter.status);
  }

  if (records.length === 0) {
    tbody.innerHTML = `<tr><td colspan="8" style="text-align:center;color:#9ca3af;padding:32px">No reports found.</td></tr>`;
    return;
  }

  tbody.innerHTML = records.map(rep => `
    <tr data-id="${rep.id}">
      <td>${rep.title}</td>
      <td>${rep.period}</td>
      <td style="text-transform:capitalize">${rep.category}</td>
      <td>${rep.scopeLabel}</td>
      <td>${rep.roi != null ? rep.roi + "%" : "—"}</td>
      <td>${rep.npv != null ? formatCurrency(rep.npv) : "—"}</td>
      <td>${badgeHTML(rep.status)}</td>
      <td class="action-cell">
        <div class="action-row">
          <button class="action-btn btn-view"   onclick="ReportModule.viewReport('${rep.id}')">View</button>
          ${can("edit")   ? `<button class="action-btn btn-edit"   onclick="ReportModule.editReport('${rep.id}')">Edit</button>` : ""}
          ${can("export") ? `<button class="action-btn btn-export" onclick="ReportModule.exportReport('${rep.id}')">Export</button>` : ""}
        </div>
        ${can("delete") ? `<button class="action-btn btn-delete" onclick="ReportModule.deleteReport('${rep.id}')">Delete</button>` : ""}
      </td>
    </tr>
  `).join("");
}

/* ── VIEW ─────────────────────────────────────────── */

export function viewReport(id) {
  const rep = FinanceDB.financialReports.find(r => r.id === id);
  if (!rep) return;

  openModal({
    title: rep.title,
    bodyHTML: `
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px 24px;font-size:14px">
        <div><strong>Period</strong><p>${rep.period}</p></div>
        <div><strong>Category</strong><p style="text-transform:capitalize">${rep.category}</p></div>
        <div><strong>Scope</strong><p>${rep.scopeLabel}</p></div>
        <div><strong>Format</strong><p>${rep.format}</p></div>
        <div><strong>ROI</strong><p>${rep.roi != null ? rep.roi + "%" : "—"}</p></div>
        <div><strong>NPV</strong><p>${rep.npv != null ? formatCurrency(rep.npv) : "—"}</p></div>
        <div><strong>Payback Period</strong><p>${rep.paybackYears != null ? rep.paybackYears + " yrs" : "—"}</p></div>
        <div><strong>Status</strong><p>${badgeHTML(rep.status)}</p></div>
        <div><strong>Generated By</strong><p>${rep.generatedBy}</p></div>
        <div><strong>Generated At</strong><p>${formatDate(rep.generatedAt)}</p></div>
      </div>
      <div style="margin-top:14px;padding:12px;background:#f9fafb;border-radius:8px;font-size:13px;color:#374151">
        <strong>Notes:</strong> ${rep.notes || "—"}
      </div>`,
    confirmLabel: "Close",
    cancelLabel: "",
    onConfirm: () => {}
  });
}

/* ── ADD ──────────────────────────────────────────── */

export function openAddReportModal() {
  if (!can("create")) { showToast("Permission denied.", "error"); return; }

  const scopeOptions = [
    ...FinanceDB.departments.map(d => `<option value="${d.name}">Dept: ${d.name}</option>`),
    ...FinanceDB.buildings.map(b => `<option value="${b.name}">Building: ${b.name}</option>`),
    `<option value="Full Campus">Campus: Full Campus</option>`
  ].join("");

  openModal({
    title: "Generate New Report",
    bodyHTML: `
      <form id="add-report-form" novalidate>
        <div class="fm-group">
          <label>Report Title *</label>
          <input id="ar-title" placeholder="e.g. Q1 2025 Energy Report" maxlength="80">
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>Period *</label>
            <input id="ar-period" placeholder="e.g. 2025-Q1 or 2025-03">
          </div>
          <div class="fm-group">
            <label>Category *</label>
            <select id="ar-category">
              <option value="">Select</option>
              <option value="energy">Energy</option>
              <option value="operations">Operations</option>
            </select>
          </div>
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>Scope *</label>
            <select id="ar-scope">
              <option value="">Select scope</option>
              ${scopeOptions}
            </select>
          </div>
          <div class="fm-group">
            <label>Format *</label>
            <select id="ar-format">
              <option value="PDF">PDF</option>
              <option value="CSV">CSV</option>
            </select>
          </div>
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>ROI (%)</label>
            <input id="ar-roi" type="number" placeholder="e.g. 18.5" min="0" max="200">
          </div>
          <div class="fm-group">
            <label>NPV ($)</label>
            <input id="ar-npv" type="number" placeholder="e.g. 148000" min="0">
          </div>
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>Payback Period (years)</label>
            <input id="ar-payback" type="number" placeholder="e.g. 2.8" min="0" step="0.1">
          </div>
          <div class="fm-group">
            <label>Viability Status *</label>
            <select id="ar-status">
              <option value="viable">Viable</option>
              <option value="marginal">Marginal</option>
              <option value="not-viable">Not Viable</option>
            </select>
          </div>
        </div>
        <div class="fm-group">
          <label>Notes</label>
          <textarea id="ar-notes" rows="2" placeholder="Optional observations..." maxlength="300"></textarea>
        </div>
      </form>`,
    confirmLabel: "Generate Report",
    onConfirm: () => _submitAddReport()
  });
}

function _submitAddReport() {
  const form = document.getElementById("add-report-form");
  if (!form) return;

  const fields = {
    title:    document.getElementById("ar-title"),
    period:   document.getElementById("ar-period"),
    category: document.getElementById("ar-category"),
    scope:    document.getElementById("ar-scope"),
    format:   document.getElementById("ar-format"),
    roi:      document.getElementById("ar-roi"),
    npv:      document.getElementById("ar-npv"),
    payback:  document.getElementById("ar-payback"),
    status:   document.getElementById("ar-status"),
    notes:    document.getElementById("ar-notes")
  };

  clearAllErrors(form);
  let valid = true;

  const rules = {
    title:    { required: true, minLength: 4, maxLength: 80 },
    period:   { required: true, pattern: /^\d{4}-(0[1-9]|1[0-2]|Q[1-4])$/, patternMsg: "Format must be YYYY-MM or YYYY-Q1 to YYYY-Q4." },
    category: { required: true },
    scope:    { required: true },
    status:   { required: true },
    roi:      { positiveNumber: true },
    npv:      { positiveNumber: true },
    payback:  { positiveNumber: true }
  };

  const data = {};
  for (const [k, el] of Object.entries(fields)) data[k] = el.value;

  const { errors } = validateForm(data, rules);
  for (const [k, msg] of Object.entries(errors)) {
    if (fields[k]) { showFieldError(fields[k], msg); valid = false; }
  }

  if (!valid) {
    return false;
  }

  const newRep = {
    id: generateId("rep"),
    title:        data.title.trim(),
    period:       data.period.trim(),
    category:     data.category,
    scope:        data.scope.includes("Campus") ? "campus" : data.scope.includes("Dept") ? "department" : "building",
    scopeLabel:   data.scope,
    generatedAt:  new Date().toISOString(),
    generatedBy:  window.FinanceDB?.session?.user?.name ?? "Analyst",
    format:       data.format,
    roi:          data.roi !== "" ? Number(data.roi) : null,
    npv:          data.npv !== "" ? Number(data.npv) : null,
    paybackYears: data.payback !== "" ? Number(data.payback) : null,
    status:       data.status,
    notes:        data.notes.trim()
  };

  FinanceDB.financialReports.unshift(newRep);
  persistData();
  logActivity("report", `Report "${newRep.title}" generated`, `Period: ${newRep.period}`);
  renderReportList();
  showToast(`Report "${newRep.title}" created.`, "success");
}

/* ── EDIT ─────────────────────────────────────────── */

export function editReport(id) {
  if (!can("edit")) { showToast("Permission denied.", "error"); return; }
  const rep = FinanceDB.financialReports.find(r => r.id === id);
  if (!rep) return;

  openModal({
    title: "Edit Report",
    bodyHTML: `
      <form id="edit-report-form" novalidate>
        <div class="fm-group">
          <label>Report Title *</label>
          <input id="er-title" value="${rep.title}" maxlength="80">
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>ROI (%)</label>
            <input id="er-roi" type="number" value="${rep.roi ?? ""}" min="0">
          </div>
          <div class="fm-group">
            <label>NPV ($)</label>
            <input id="er-npv" type="number" value="${rep.npv ?? ""}" min="0">
          </div>
        </div>
        <div class="fm-row">
          <div class="fm-group">
            <label>Payback (years)</label>
            <input id="er-payback" type="number" value="${rep.paybackYears ?? ""}" min="0" step="0.1">
          </div>
          <div class="fm-group">
            <label>Status *</label>
            <select id="er-status">
              ${["viable","marginal","not-viable"].map(s =>
                `<option value="${s}" ${s === rep.status ? "selected":""}>${s.charAt(0).toUpperCase()+s.slice(1).replace("-"," ")}</option>`
              ).join("")}
            </select>
          </div>
        </div>
        <div class="fm-group">
          <label>Notes</label>
          <textarea id="er-notes" rows="3" maxlength="300">${rep.notes ?? ""}</textarea>
        </div>
      </form>`,
    confirmLabel: "Save Changes",
    onConfirm: () => _submitEditReport(id)
  });
}

function _submitEditReport(id) {
  const form = document.getElementById("edit-report-form");
  if (!form) return;

  const fields = {
    title:   document.getElementById("er-title"),
    roi:     document.getElementById("er-roi"),
    npv:     document.getElementById("er-npv"),
    payback: document.getElementById("er-payback"),
    status:  document.getElementById("er-status"),
    notes:   document.getElementById("er-notes")
  };

  clearAllErrors(form);
  let valid = true;
  const data = {};
  for (const [k, el] of Object.entries(fields)) data[k] = el.value;

  const rules = {
    title:   { required: true, minLength: 4, maxLength: 80 },
    status:  { required: true },
    roi:     { positiveNumber: true },
    npv:     { positiveNumber: true },
    payback: { positiveNumber: true }
  };

  const { errors } = validateForm(data, rules);
  for (const [k, msg] of Object.entries(errors)) {
    if (fields[k]) { showFieldError(fields[k], msg); valid = false; }
  }

  if (!valid) {
    return false;
  }

  const idx = FinanceDB.financialReports.findIndex(r => r.id === id);
  FinanceDB.financialReports[idx] = {
    ...FinanceDB.financialReports[idx],
    title:        data.title.trim(),
    roi:          data.roi !== "" ? Number(data.roi) : null,
    npv:          data.npv !== "" ? Number(data.npv) : null,
    paybackYears: data.payback !== "" ? Number(data.payback) : null,
    status:       data.status,
    notes:        data.notes.trim()
  };

  persistData();
  logActivity("report", `Report "${data.title}" updated`, `Status: ${data.status}`);
  renderReportList();
  showToast("Report updated.", "success");
}

/* ── DELETE ───────────────────────────────────────── */

export function deleteReport(id) {
  if (!can("delete")) { showToast("Permission denied.", "error"); return; }
  const rep = FinanceDB.financialReports.find(r => r.id === id);
  if (!rep) return;

  openModal({
    title: "Delete Report",
    bodyHTML: `<p>Delete <strong>"${rep.title}"</strong>? This cannot be undone.</p>`,
    confirmLabel: "Delete",
    danger: true,
    onConfirm: () => {
      FinanceDB.financialReports = FinanceDB.financialReports.filter(r => r.id !== id);
      persistData();
      logActivity("report", `Report "${rep.title}" deleted`, "");
      renderReportList();
      showToast("Report deleted.", "success");
    }
  });
}

/* ── EXPORT (simulated) ───────────────────────────── */

export function exportReport(id) {
  if (!can("export")) { showToast("Permission denied.", "error"); return; }
  const rep = FinanceDB.financialReports.find(r => r.id === id);
  if (!rep) return;
  showToast(`Exporting "${rep.title}" as ${rep.format}…`, "info");
  setTimeout(() => showToast(`"${rep.title}" exported successfully.`, "success"), 1400);
}

/* ── EXPORT NAMESPACE ─────────────────────────────── */
const ReportModule = { renderReportList, viewReport, openAddReportModal, editReport, deleteReport, exportReport };
window.ReportModule = ReportModule;
export default ReportModule;
